apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-claim
spec:
  storageClassName: manual
  #storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi